const names = {
    "slub": "ślub",
    "slubu": "ślubu",
    "slubowi": "ślubowi",
    "slubem": "ślubem",
    "slubie": "ślubie",
    "gosc": "gość",
    "goscia": "gościa",
    "gosciu": "gościu",
    "goscie": "goście",
    "gosci": "gości",
    "blogoslawienstwo": "błogosławieństwo",
    "blogoslawienstwem": "błogosławieństwem",
    "przebierancy": "przebierańcy",
    "kosciol": "kościół",
    "kosciola": "kościoła",
    "kosciele": "kościele",
    "zyczenia": "życzenia",
    "przyjecie": "przyjęcie",
    "przyjeciu": "przyjęciu",
    "przyjecia": "przyjęcia",
    "podziekowanie": "podziękowanie",
    "strazacy": "strażacy",
    "polnoc": "północ",
    "mlody": "młody",
    "miesiac miodowy": "miesiąc miodowy",
    "zaproszenie": "zaproszenie",
    "obraczki": "obrączki",
    "obraczek": "obrączek",
    "ksiadz": "ksiądz",
    "slubna": "ślubna",
    "slubny": "ślubny",
    "slubne": "ślubne",
    "wozek": "wózek",
    "kwiaty": "kwiaty",
    "stoly": "stoły",
    "stol": "stół",
    "mloda": "młoda",
    "swiadek": "świadek",
    "wystep": "występ",
    "poslubna": "poślubna",
    "podziekowania": "podziękowania",
    "sluby": "śluby",
    "slubow": "ślubów",
    "slubom": "ślubom",
    "slubami": "ślubami",
    "o slubie": "o ślubie",
    "o slubach": "o ślubach",
    "gosciowi": "gościowi",
    "gosciom": "gościom",
    "koscioly": "kościoły",
    "kosciolow": "kościołów",
    "kosciolowi": "kościołowi",
    "kosciolom": "kościołom",
    "kosciolem": "kościołem",
    "kosciolami": "kościołami",
    "o kosciol": "o kościele",
    "o kosciolach": "o kościołach",
    "kosciolu": "kościele",
    "mlodzi": "młodzi",
    "mlodego": "młodego",
    "mlodych": "młodych",
    "mlodemu": "młodemu",
    "mlodym": "młodym",
    "mlodymi": "młodymi",
    "o mlodym": "o młodym",
    "o mlodych": "o młodych",
    "mlode": "młode",
    "mlodej": "młodej",
    "o mlodej": "o młodej",
    "obraczka": "obrączka",
    "obraczkami": "obrączkami",
    "obraczkom": "obrączkom",
    "o obraczce": "o obrączce",
    "o obraczkach": "o obrączkach",
    "obraczko": "obrączko",
    "wozki": "wozki",
    "wozka": "wozka",
    "wozkowi": "wozkowi",
    "wozkom": "wozkom",
    "wozkiem": "wozkiem",
    "wozkami": "wozkami",
    "o wozku": "o wózku",
    "o wozkach": "o wózkach",
    "wozku": "wozku",
    "stolu": "stołu",
    "stolow": "stołów",
    "stolowi": "stolowi",
    "stolom": "stolom",
    "stolem": "stołem",
    "stolami": "stołami",
    "o stole": "o stole",
    "o stolach": "o stołach",
    "stole": "stole",
    "podziekowan": "podziękowań",
    "podziekowaniu": "podziękowaniu",
    "podziekowaniom": "podziękowaniom",
    "podziekowaniem": "podziękowaniem",
    "podziekowaniami": "podziękowaniami",
    "o podziekowaniu": "o podziękowaniu",
    "o podziekowaniach": "o podziękowaniach",
    "blogoslawienstwa": "błogosławieństwa",
    "blogoslawienstw": "błogosławieństw",
    "blogoslawienstwu": "błogosławieństwu",
    "blogoslawienstwom": "błogosławieństwom",
    "blogoslawienstwami": "błogosławieństwami",
    "o blogoslawienstwie": "o błogosławieństwie",
    "o blogoslawienstwach": "o błogosławieństwach",
    "blogoslawienstwie": "błogosławieństwie"
} as { [name: string]: string };

export const getDirectoryName = (directoryName: string) => {
    const wordsInDirectoryName = directoryName.split(' ');
    const fixedWords = wordsInDirectoryName.map((w) => names[w] ?? w);

    return fixedWords.join(' ');
};
