# This is a basic workflow to help you get started with Actions

name: Client

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_gallery:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true

      - run: yarn install
        working-directory: ./gallery

      - run: yarn run build
        working-directory: ./gallery

      - uses: actions/upload-artifact@v2
        with:
          name: build_gallery
          path: ./gallery/dist

  build_site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true

      - run: yarn install
        working-directory: ./site

      - run: yarn run build:prod
        working-directory: ./site

      - uses: actions/upload-artifact@v2
        with:
          name: build_site
          path: ./site/dist

  build_panel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true

      - run: yarn install
        working-directory: ./panel

      - run: yarn run build:prod
        working-directory: ./panel

      - uses: actions/upload-artifact@v2
        with:
          name: build_panel
          path: ./panel/dist

  build_utils:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true

      - run: yarn install
        working-directory: ./utils

      - run: yarn run build
        working-directory: ./utils

      - uses: actions/upload-artifact@v2
        with:
          name: build_utils
          path: ./utils

  build_api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true

      - run: yarn install
        working-directory: ./api

      - run: yarn run build
        working-directory: ./api

      - uses: actions/upload-artifact@v2
        with:
          name: build_api
          path: ./api

  build_gallery-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true

      - run: yarn install
        working-directory: ./gallery-server

      - run: yarn run build
        working-directory: ./gallery-server

      - uses: actions/upload-artifact@v2
        with:
          name: build_gallery-server
          path: ./gallery-server

  build_server:
    needs: [build_site, build_panel, build_gallery, build_utils, build_api, build_gallery-server]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - uses: actions/download-artifact@v2
        with:
          name: build_site
          path: ./site/dist

      - uses: actions/download-artifact@v2
        with:
          name: build_panel
          path: ./panel/dist

      - uses: actions/download-artifact@v2
        with:
          name: build_gallery
          path: ./gallery/dist

      - uses: actions/download-artifact@v2
        with:
          name: build_utils
          path: ./utils

      - uses: actions/download-artifact@v2
        with:
          name: build_api
          path: ./api

      - uses: actions/download-artifact@v2
        with:
          name: build_gallery-server
          path: ./gallery-server

      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
          check-latest: true

      - run: yarn install --production
        working-directory: ./server

      - run: yarn run build
        working-directory: ./server

      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r package/package.zip node_modules server

      - name: upload artifact
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./package/
          server-dir: domains/kuchasz.usermd.net/
