# This is a basic workflow to help you get started with Actions

name: Master.Publish.Prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

jobs:
    publish_application:
        runs-on: ubuntu-latest

        steps:
            - name: publish into production
              uses: garygrossgarten/github-action-ssh@release
              with:
                  host: ${{ secrets.ssh_host }}
                  username: ${{ secrets.ssh_username }}
                  password: ${{ secrets.ssh_password }}
                  tryKeyboard: true
                  command: |
                      cd domains/pyszstudio.pl/
                      rm -rf node_modules
                      mv public_nodejs/public/blogs images_backup
                      mv public_nodejs/databases databases_backup
                      rm -rf public_nodejs
                      unzip -q ../artifacts/package.zip
                      mv -f packages/server public_nodejs
                      mv -f public_nodejs/dist/* public_nodejs/
                      mkdir public_nodejs/public
                      mv -f images_backup public_nodejs/public/blogs
                      mv -f databases_backup public_nodejs/databases
                      cd public_nodejs
                      npm install sharp@0.32.3 sqlite3
                      devil www restart pyszstudio.pl
