# This is a basic workflow to help you get started with Actions

name: Publish-Prod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_application:
    runs-on: ubuntu-latest

    steps:
      - name: publish into staging
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.prod_ssh_host }}
          username: ${{ secrets.prod_ssh_username }}
          password: ${{ secrets.prod_ssh_password }}
          tryKeyboard: true
          command: |
            cd domains/www.pyszstudio.pl/
            rm -rf node_modules
            mv public_nodejs/public images_backup
            mv public_nodejs/databases databases_backup
            rm -rf public_nodejs
            unzip package.zip
            mv server public_nodejs
            mv images_backup public_nodejs/public
            mv databases_backup public_nodejs/databases
            cd public_nodejs
            npm install sqlite3
            npm install sharp
            devil www restart www.pyszstudio.pl