# This is a basic workflow to help you get started with Actions

name: Master.Publish.Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    publish_application:
        runs-on: ubuntu-latest

        steps:
            - name: publish into staging
              uses: fifsky/ssh-action@master
              with:
                  host: ${{ secrets.ssh_host }}
                  username: ${{ secrets.ssh_username }}
                  password: ${{ secrets.ssh_password }}
                  script: |
                      cd domains/kuchasz.usermd.net/ && \
                      rm -rf node_modules && \
                      mv public_nodejs/public/blogs images_backup && \
                      mv public_nodejs/databases databases_backup && \
                      rm -rf public_nodejs && \
                      rm -rf packages && \
                      rm -rf node_modules && \
                      unzip -o -q ../artifacts/package.zip && \
                      mv -f packages/server/dist/* packages/server/ && \
                      mkdir -p packages/server/public && \
                      mv -f images_backup packages/server/public/blogs && \
                      mv -f databases_backup packages/server/databases && \
                      mv -f packages/server public_nodejs && \
                      devil www restart kuchasz.usermd.net
