# This is a basic workflow to help you get started with Actions

name: Master.Publish.Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    publish_application:
        runs-on: ubuntu-latest

        steps:
            - name: publish into staging
              uses: garygrossgarten/github-action-ssh@release
              with:
                  host: ${{ secrets.ssh_host }}
                  username: ${{ secrets.ssh_username }}
                  password: ${{ secrets.ssh_password }}
                  tryKeyboard: true
                  command: |
                      cd domains/kuchasz.usermd.net/
                      rm -rf node_modules
                      cp public_nodejs/public images_backup
                      cp public_nodejs/databases databases_backup
                      rm -rf public_nodejs
                      unzip -q ../artifacts/package.zip
                      cp packages/server/dist public_nodejs
                      cp packages/api/dist node_modules/@pp/api/dist
                      cp packages/gallery/dist node_modules/@pp/gallery/dist
                      cp packages/gallery-server/dist node_modules/@pp/gallery-server/dist
                      cp packages/panel/dist node_modules/@pp/panel/dist
                      cp packages/site/dist node_modules/@pp/site/dist
                      cp packages/utils/dist node_modules/@pp/utils/dist
                      mv images_backup public_nodejs/public
                      mv databases_backup public_nodejs/databases
                      devil www restart kuchasz.usermd.net
