# This is a basic workflow to help you get started with Actions

name: Master.Publish.Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    publish_application:
        runs-on: ubuntu-latest

        steps:
            - name: publish into staging
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  script: |
                      cd domains/staging.pyszstudio.pl/ && \
                      rm -rf node_modules && \
                      [ -d "public_nodejs/public/blogs" ] && mv public_nodejs/public/blogs images_backup || true && \
                      [ -d "public_nodejs/databases" ] && mv public_nodejs/databases databases_backup || true && \
                      rm -rf public_nodejs && \
                      rm -rf packages && \
                      rm -rf node_modules && \
                      unzip -o -q ../artifacts/package.zip && \
                      mv -f packages/server/dist/* packages/server/ && \
                      mkdir -p packages/server/public && \
                      [ -d "images_backup" ] && mv -f images_backup packages/server/public/blogs || true && \
                      [ -d "databases_backup" ] && mv -f databases_backup packages/server/databases || true && \
                      mv -f packages/server public_nodejs && \
                      npm install -w @pp/server node-addon-api && \
                      npm install -w @pp/server node-gyp && \
                      npm install -w @pp/server sharp@0.33.3 && \
                      npm install -w @pp/server sqlite3 && \
                      npm install -w @pp/gallery sqlite3 && \
                      cp .env public_nodejs && \
                      devil www restart staging.pyszstudio.pl